### PR TITLE
add empirical interpolation to affinely decompose Woods-Saxon potential

### PR DESCRIPTION
**Pull request by beykyle**
This could still use a little cleaning. When I get a chance, I'd like to:
- clean it up a bit
- add greedy algo for choosing `s` points
- use the affinely decomposed potential to construct an RBM emulator

I tried to keep a similar writing tone as you guys. Lmk if you have any comments, feel free to incorporate as much or as little of this into the actual repo.

### CODE REVIEW

**Comment by kylegodbey** [comment]
This is great! Sorry for the long delay getting back to you -- it's a busy time of year.

I have two main suggestions and Pablo will read it as well and give some feedback if he has any.

1. Separate this notebook into a new section called "Empirical Interpolation Method". You can copy all the preamble needed to make the code work, but I think it works better as two standalone notebooks.

This way the book is more methods focused and will make it easier to find the EIM information and not clutter the "vintage" approach. We'll put the two current applications into a first section, but we haven't decided the name yet.

2. Add yourself to the list of contributors! That part is arguably more important 😄

**Comment by beykyle** [comment]
Thanks for the feedback! Will do.

**Comment by pabggpnMSU** [comment]
Hey Kyle B! This is FANTASTIC! I am so so happy you were able to sit down and do this :D. 

I am sorry it took us so long to get back to you, it has indeed been super busy times. 

I would like to help with editing it a bit so we can put it in excellent shape and add it to the book. I will be super mega busy until next week but then I'll help. For now, I have three of suggestions in case you want to go for them (if you are also busy that is ok of course).

1. Since this is a public thing that we want everyone to access, it would be better to avoid too informal language (like "this is hacky af"). Could you clean those comments a little bit? 

2. RBMs are not great when you have things that move in the "x" (or "r") direction, like a propagating wave. I will expect that this will not be awesome if we have to emulate how the potential changes when you move big S from 2 to 10, is a lot of change. If that were the actual physical range we will probably divide it into several emulators for different ranges of S. For the physical case of interest, I think the radius are known within 10% accuracy or less (correct me if I am wrong). Maybe having a smaller range would be better and more realistic.

3. Once we have the emulated potential, we should check out what we get on the other side of the emulated wave function. Could you put the potential we obtain for the smaller radius range in the radial equation, solve for the RB wave function, and compare with the exact solver? That way we can finish this notebook with the same plot of emulated vs high fidelity that the other has.

Once again, don't feel obligated to do any of this, I can help starting next week and what you have done already is super cool!

**Comment by pabggpnMSU** [comment]
WOWOWOW it looks super cool now, congrats Kyle!

Will look at it with more detail tomorrow or Friday. Thank you very much for implementing everything!

**Comment by beykyle** [comment]
Hey @pabggpnMSU, thanks for the feedback! 

I primarily addressed pts. 2 and 3 . I think this probably needs some more editing for tone/language to bring it up to standard. I also left in some comments were I do things in a non-pythonic way - feel free to work your python magic and  make them less hacky, or remove the comments. 

This was fun to work on, thanks for letting me contribute!

**Comment by pabggpnMSU** [comment]
Kyle, you are awesome! Thank you very much for writing that up so quickly. I will help with the editing and Kyle will probably also help with that and the coding. We will get this up soon!

Pablo
________________________________

**Pull request merged**
